- name: install mongodb component
  hosts: mongodb
  become: yes
  tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
      
  - name: Install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed

  - name: Enable service mongodb, and start the service
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: started

  - name: replace the text
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Restart Mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted
    